export const portfolioData = {
  Home: {
    name: "Armaan",
    punchLine1: "Full Stack Web Developer.",
    punchLine2: "Solid backend. Clean UI. Smooth UX.",
    punchLine3: "Fast. Responsive. Beautiful.",
    cta: "Download Resume",
    description:
      "I build full-stack web applications with modern UI, smooth UX, and scalable backend systems.",
  },

  projects: [
    {
      id: 1,
      order: 1,
      title: "Api Monitoring System",
      description:
        "A real-time API monitoring system that tracks endpoint health, response times, and failure rates. It provides alerts, logs, and analytics to help ensure system reliability and quick issue detection.",
      tech: ["Express", "React", "MongoDB", "PostgreSQL"],
      github: "https://github.com/armaanchakla/api-monitoring-system",
      live: "",
    },
    {
      id: 2,
      order: 2,
      title: "MovieZone",
      description:
        "MovieZone is a movie discovery platform integrated with the TMDB API, enabling real-time access to movie data including trending titles, ratings, genres, cast details, and trailers, delivered through a fast and responsive interface.",
      tech: ["React", "Node", "Vite", "TailwindCSS"],
      github: "https://github.com/armaanchakla/react-movie-app",
      live: "",
    },
    {
      id: 3,
      order: 3,
      title: "File Share System",
      description:
        "A full-stack file sharing system with secure upload, storage, and link-based access control. It is optimized for performance, reliability, and efficient file management.",
      tech: ["Express", "MongoDB", "React", "Node"],
      github: "https://github.com/armaanchakla/FileSharingApiServer",
      live: "",
    },
    {
      id: 4,
      order: 4,
      title: "Job Point",
      description:
        "Job Point is a full-stack job portal with role-based access for employers and candidates. It supports job posting, advanced search, application management, and a responsive UI for seamless user experience.",
      tech: ["React", "Vite", "TailwindCSS"],
      github: "https://github.com/armaanchakla/react-job-app",
      live: "",
    },
    {
      id: 5,
      order: 5,
      title: "Armaan Portfolio",
      description:
        "A responsive developer portfolio built to showcase full-stack projects, technical skills, and experience with a focus on clean design, performance, and smooth user interaction.",
      tech: ["React", "Vite", "TailwindCSS"],
      github: "https://github.com/armaanchakla/portfolio",
      live: "https://armaanchakla.vercel.app/",
    },
  ],

  skills: [
    "Laravel",
    "Node",
    "Express",
    "Loopback",
    "React",
    "Vue",
    "PHP",
    "JavaScript",
    "TypeScript",
    "TailwindCSS",
    "MySQL",
    "PostgreSQL",
    "MongoDB",
    "Bootstrap",
    "REST API Design",
    "SOAP API Integration",
    "OAuth 2.0",
    "JWT Authentication",
    "Token Management",
    "Passport",
    "Sanctum",
    "Redis",
    "RabbitMQ",
    "Kafka",
    "AWS",
    "GitHub Action",
    "Docker",
    "Git",
    "Query Optimization",
    "DB Tuning",
    "Load Balancing",
    "Rocky Linux",
    "CentOS",
    "Supervisor",
    "Screen Session",
    "Nginx",
    "Cross-Platform",
    "Full-Stack",
    "Layered Arch",
    "Scalable Systems",
    "MVC Pattern",
    "Microservices",
    "Static Analysis",
  ],

  contact: {
    email: "mailto:armaansanjeed@gmail.com",
    github: "https://github.com/armaanchakla",
    linkedin: "https://linkedin.com/in/armaanchakla",
  },
};
